# 1. Control de Memoria JVM para Gradle
org.gradle.jvmargs=-Xmx3072M -XX:MaxMetaspaceSize=1024M -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError

# 2. Aceleración de Compilación y Caché
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.daemon=true
org.gradle.vfs.watch=true
kotlin.daemon.jvmargs=-Xmx1536M

# 3. Optimizaciones de Android y R8
android.useAndroidX=true
android.enableJetifier=true
android.nonTransitiveRClass=true
android.enableR8.fullMode=true

# 4. Compatibilidad de Migración Flutter
android.builtInKotlin=false
android.newDsl=false
